version: '3.9'
services:
  api-server:
    container_name: api-server
    build: ./backend
    environment:
      - PORT=8080
      - PORT_NN_API=8081
    ports:
      - "8080:8080"

  nn_api:
    container_name: nn-api-server
    build: ./nn
    environment:
      - PORT=8081